blueprint:
  name: Zonneplan Thuisbatterij Optimalisatie (gepatcht: optionele sensoren niet verplicht)
  description: >
    Aansturing van thuisbatterij met prijsdrempel (dynamic_charging ↔ home_optimization),
    categoriegestuurd ontladen, dynamische reserve op basis van forecast +1..+8,
    optionele anti-rondpompen en optionele verbruik-blokker (bv. EV-laadpaal).
    Deze gepatchte versie verwijdert optionele sensoren uit de triggers, zodat de automation
    ook zonder die entiteiten kan worden opgeslagen.
  domain: automation

  input:
    # ---- Sensors ----
    sensor_current_price:
      name: "Huidige stroomprijs (€/kWh)"
      description: "Bijvoorbeeld: sensor.zonneplan_current_electricity_tariff"
      selector:
        entity:
          domain: sensor
    sensor_current_group:
      name: "Huidige prijscategorie (low/medium/high)"
      description: "Bijvoorbeeld: sensor.zonneplan_current_tariff_group"
      selector:
        entity:
          domain: sensor
    sensor_soc:
      name: "Batterij SOC (%)"
      description: "Bijvoorbeeld: sensor.nexus_solarman_battery"
      selector:
        entity:
          domain: sensor

    # Forecast (8 uur)
    forecast_h1:
      name: "Forecast categorie +1 uur"
      description: "Bijvoorbeeld: sensor.zonneplan_forecast_tariff_group_hour_1"
      selector:
        entity:
          domain: sensor
    forecast_h2:
      name: "Forecast categorie +2 uur"
      description: "Bijvoorbeeld: sensor.zonneplan_forecast_tariff_group_hour_2"
      selector:
        entity:
          domain: sensor
    forecast_h3:
      name: "Forecast categorie +3 uur"
      description: "Bijvoorbeeld: sensor.zonneplan_forecast_tariff_group_hour_3"
      selector:
        entity:
          domain: sensor
    forecast_h4:
      name: "Forecast categorie +4 uur"
      description: "Bijvoorbeeld: sensor.zonneplan_forecast_tariff_group_hour_4"
      selector:
        entity:
          domain: sensor
    forecast_h5:
      name: "Forecast categorie +5 uur"
      description: "Bijvoorbeeld: sensor.zonneplan_forecast_tariff_group_hour_5"
      selector:
        entity:
          domain: sensor
    forecast_h6:
      name: "Forecast categorie +6 uur"
      description: "Bijvoorbeeld: sensor.zonneplan_forecast_tariff_group_hour_6"
      selector:
        entity:
          domain: sensor
    forecast_h7:
      name: "Forecast categorie +7 uur"
      description: "Bijvoorbeeld: sensor.zonneplan_forecast_tariff_group_hour_7"
      selector:
        entity:
          domain: sensor
    forecast_h8:
      name: "Forecast categorie +8 uur"
      description: "Bijvoorbeeld: sensor.zonneplan_forecast_tariff_group_hour_8"
      selector:
        entity:
          domain: sensor

    # ---- Actuators ----
    select_mode:
      name: "Battery control mode select (dynamic_charging | home_optimization)"
      description: "Bijvoorbeeld: select.thuisbatterij_battery_control_mode"
      selector:
        entity:
          domain: select
    number_charge_power:
      name: "Max charge power (W)"
      description: "Bijvoorbeeld: number.thuisbatterij_max_charge_power_home_optimization"
      selector:
        entity:
          domain: number
    number_discharge_power:
      name: "Max discharge power (W)"
      description: "Bijvoorbeeld: number.thuisbatterij_max_discharge_power_home_optimization"
      selector:
        entity:
          domain: number

    # ---- Drempels ----
    price_floor:
      name: "Prijsdrempel voor ontladen (€/kWh)"
      default: 0.20
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
          unit_of_measurement: "€/kWh"
          mode: slider
    soc_reserve_min:
      name: "Minimale reserve-SOC (%)"
      default: 35
      selector:
        number:
          min: 0
          max: 80
          step: 5
          unit_of_measurement: "%"
          mode: slider
    soc_low_floor:
      name: "LOW-categorie SOC-drempel voor beperkte ondersteuning (%)"
      default: 80
      selector:
        number:
          min: 50
          max: 100
          step: 5
          unit_of_measurement: "%"
          mode: slider

    # ---- Vermogens (W) ----
    power_high:
      name: "HIGH - ontlaadvermogen (W)"
      default: 6000
      selector:
        number:
          min: 0
          max: 10000
          step: 100
          unit_of_measurement: "W"
          mode: slider
    power_medium:
      name: "MEDIUM - ontlaadvermogen (W)"
      default: 1500
      selector:
        number:
          min: 0
          max: 10000
          step: 100
          unit_of_measurement: "W"
          mode: slider
    power_low_cap:
      name: "LOW - beperkt ontlaadvermogen (W)"
      default: 1000
      selector:
        number:
          min: 0
          max: 10000
          step: 100
          unit_of_measurement: "W"
          mode: slider
    power_charge_when_cheap:
      name: "Laden bij goedkope prijs (W)"
      default: 8000
      selector:
        number:
          min: 0
          max: 10000
          step: 100
          unit_of_measurement: "W"
          mode: slider

    # ---- Forecast → dynamische reserve ----
    dyn_res_high_0_2h:
      name: "Reserve bij HIGH binnen 0–2 uur (%)"
      default: 55
      selector:
        number:
          min: 0
          max: 100
          step: 5
          unit_of_measurement: "%"
          mode: slider
    dyn_res_high_2_4h:
      name: "Reserve bij HIGH binnen 2–4 uur (%)"
      default: 45
      selector:
        number:
          min: 0
          max: 100
          step: 5
          unit_of_measurement: "%"
          mode: slider
    dyn_res_medium_0_2h:
      name: "Reserve bij MEDIUM binnen 0–2 uur (%)"
      default: 40
      selector:
        number:
          min: 0
          max: 100
          step: 5
          unit_of_measurement: "%"
          mode: slider
    dyn_res_high_4_8h:
      name: "Reserve bij HIGH binnen 4–8 uur (%)"
      default: 40
      selector:
        number:
          min: 0
          max: 100
          step: 5
          unit_of_measurement: "%"
          mode: slider
    dyn_res_medium_4_8h:
      name: "Reserve bij MEDIUM binnen 4–8 uur (%)"
      default: 35
      selector:
        number:
          min: 0
          max: 100
          step: 5
          unit_of_measurement: "%"
          mode: slider

    # ---- Anti-rondpompen (optioneel) ----
    sensor_house_power:
      name: "Huidig huis-/netvermogen (W) (optioneel)"
      description: "Bijvoorbeeld: sensor.connect_energiemeter_electricity_consumption (positief = afname, negatief = export)"
      default: ""
      selector:
        entity:
          domain: sensor
    min_discharge_net_load_w:
      name: "Minimale net-/huislast om te mogen ontladen (W)"
      default: 300
      selector:
        number:
          min: 0
          max: 2000
          step: 50
          unit_of_measurement: "W"
          mode: slider

    # ---- Verbruik-blokker (optioneel) ----
    sensor_block_discharge:
      name: "Blokker verbruikssensor (W) (optioneel)"
      description: "Bijvoorbeeld: sensor.charge_laadstation_kwh_charge_point_power"
      default: ""
      selector:
        entity:
          domain: sensor
    block_discharge_threshold_w:
      name: "Blokker-drempel (W) — vanaf dit verbruik NIET ontladen"
      default: 0
      selector:
        number:
          min: 0
          max: 20000
          step: 50
          unit_of_measurement: "W"
          mode: slider

variables:
  v_price: !input sensor_current_price
  v_cat: !input sensor_current_group
  v_soc: !input sensor_soc
  v_f1: !input forecast_h1
  v_f2: !input forecast_h2
  v_f3: !input forecast_h3
  v_f4: !input forecast_h4
  v_f5: !input forecast_h5
  v_f6: !input forecast_h6
  v_f7: !input forecast_h7
  v_f8: !input forecast_h8
  v_select_mode: !input select_mode
  v_num_charge: !input number_charge_power
  v_num_discharge: !input number_discharge_power
  v_house_pwr: !input sensor_house_power

  v_price_floor: !input price_floor
  v_soc_reserve_min: !input soc_reserve_min
  v_soc_low_floor: !input soc_low_floor

  v_p_high: !input power_high
  v_p_med:  !input power_medium
  v_p_low:  !input power_low_cap
  v_p_charge: !input power_charge_when_cheap

  v_dyn_high_0_2: !input dyn_res_high_0_2h
  v_dyn_high_2_4: !input dyn_res_high_2_4h
  v_dyn_med_0_2: !input dyn_res_medium_0_2h
  v_dyn_high_4_8: !input dyn_res_high_4_8h
  v_dyn_med_4_8:  !input dyn_res_medium_4_8h

  v_min_net_load: !input min_discharge_net_load_w

  v_block_sensor: !input sensor_block_discharge
  v_block_threshold: !input block_discharge_threshold_w

trigger:
  - platform: state
    entity_id:
      - !input sensor_current_price
      - !input sensor_current_group
      - !input sensor_soc
    for: "00:00:10"
  - platform: time_pattern
    minutes: "/5"

condition: []

action:
  - variables:
      price: "{{ states(v_price) | float(0) }}"
      cat: "{{ states(v_cat) | lower }}"
      soc: "{{ states(v_soc) | float(0) }}"
      fc: >
        {{ [
          states(v_f1)|lower, states(v_f2)|lower, states(v_f3)|lower, states(v_f4)|lower,
          states(v_f5)|lower, states(v_f6)|lower, states(v_f7)|lower, states(v_f8)|lower
        ] }}

  # Dynamische reserve obv forecast (agressief voor 0–4h, mild voor 4–8h)
  - variables:
      dyn_reserve: >-
        {% set base = v_soc_reserve_min | float(35) %}
        {% set soon_high = 'high' in fc[0:2] %}
        {% set near_high = 'high' in fc[2:4] %}
        {% set later_high = 'high' in fc[4:8] %}
        {% set soon_med  = 'medium' in fc[0:2] %}
        {% set later_med = 'medium' in fc[4:8] %}
        {% if soon_high %} {{ [base, (v_dyn_high_0_2 | float(55))] | max }}
        {% elif near_high %} {{ [base, (v_dyn_high_2_4 | float(45))] | max }}
        {% elif soon_med  %} {{ [base, (v_dyn_med_0_2  | float(40))] | max }}
        {% elif later_high %} {{ [base, (v_dyn_high_4_8 | float(40))] | max }}
        {% elif later_med  %} {{ [base, (v_dyn_med_4_8  | float(35))] | max }}
        {% else %}           {{ base }}
        {% endif %}

  # Anti-rondpompen + EV-blokker: optioneel (alleen als inputs gezet zijn)
  - variables:
      house_pwr_ok: >-
        {% if v_house_pwr in ['', None] %}
          true
        {% else %}
          {% set p = states(v_house_pwr) | float(0) %}
          {% set minp = v_min_net_load | float(300) %}
          {{ p >= minp }}
        {% endif %}
      block_ev: >-
        {% if v_block_sensor in ['', None] %}
          false
        {% else %}
          {% set ev = states(v_block_sensor) | float(0) %}
          {% set thr = v_block_threshold | float(0) %}
          {{ ev >= thr and thr > 0 }}
        {% endif %}

  # Moduswissel op basis van prijsdrempel
  - choose:
      - conditions: "{{ price < (v_price_floor | float(0.20)) }}"
        sequence:
          - service: select.select_option
            target:
              entity_id: !input select_mode
            data:
              option: "dynamic_charging"
          - service: number.set_value
            target:
              entity_id: !input number_discharge_power
            data:
              value: 0
          - service: number.set_value
            target:
              entity_id: !input number_charge_power
            data:
              value: "{{ v_p_charge }}"

      - conditions: "{{ price >= (v_price_floor | float(0.20)) }}"
        sequence:
          - service: select.select_option
            target:
              entity_id: !input select_mode
            data:
              option: "home_optimization"
          - choose:
              - conditions: "{{ block_ev or soc <= (dyn_reserve | float(35)) }}"
                sequence:
                  - service: number.set_value
                    target:
                      entity_id: !input number_discharge_power
                    data:
                      value: 0

              - conditions: "{{ house_pwr_ok and cat == 'high' }}"
                sequence:
                  - service: number.set_value
                    target:
                      entity_id: !input number_discharge_power
                    data:
                      value: "{{ v_p_high }}"
              - conditions: "{{ house_pwr_ok and cat == 'medium' }}"
                sequence:
                  - service: number.set_value
                    target:
                      entity_id: !input number_discharge_power
                    data:
                      value: "{{ v_p_med }}"
              - conditions: "{{ cat == 'low' }}"
                sequence:
                  - choose:
                      - conditions: "{{ house_pwr_ok and (soc >= (v_soc_low_floor | float(80))) }}"
                        sequence:
                          - service: number.set_value
                            target:
                              entity_id: !input number_discharge_power
                            data:
                              value: "{{ v_p_low }}"
                    default:
                      - service: number.set_value
                        target:
                          entity_id: !input number_discharge_power
                        data:
                          value: 0

mode: single
